import prisma from "@/lib/prismaClient";
import { Prisma } from "@prisma/client";

const franchiseArr: Prisma.franchiseCreateManyInput[] = [
  {
    name: "DC",
    banner: "https://the-collector-images.s3.us-east-2.amazonaws.com/dc-banner",
  },
  {
    name: "Marvel",
    banner:
      "https://the-collector-images.s3.us-east-2.amazonaws.com/marvel-banner",
  },
  {
    name: "Star Wars",
    banner:
      "https://the-collector-images.s3.us-east-2.amazonaws.com/star-wars-banner",
  },
  {
    name: "Harry potter",

    banner:
      "https://the-collector-images.s3.us-east-2.amazonaws.com/harry-potter-banner",
  },
];

const itemArr: Prisma.ItemCreateManyInput[] = [
  {
    name: "mk1",
    franchise: "marvel",
    from: "iron man 1",
    price: "100K",
    timeStamp: "30 mins",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/mk1.jpg",
  },
  {
    name: "stark industries bomb",
    franchise: "marvel",
    price: "2K",
    timeStamp: "5 min",
    from: "iron man 1",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/stark-bomb.jpeg",
  },
  {
    name: "Iron monger suit",
    franchise: "marvel",
    price: "150k",
    timeStamp: "1hr 30min",
    from: "iron man 1",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/iron-monger.png",
  },
  {
    name: "Tobby Maguire's Suit",
    franchise: "marvel",
    from: "Spiderman: No Way Home",
    price: "50k",
    timeStamp: "47min",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/tobeys-suit.jpeg",
  },
  {
    name: "Spider Man's Stark Suit",
    franchise: "marvel",
    from: "Spiderman: No Way Home",
    timeStamp: "50mins",
    price: "55k",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/stark-suit.png",
  },
  {
    name: "Stormbreaker",
    from: "Avengers end game",
    price: "4k",
    timeStamp: "1 hr and 10mins",
    franchise: "marvel",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/stormbreaker.jpeg",
  },
  {
    franchise: "DC",
    from: "Justice league Batman v superman",
    name: "Batman mech suit",
    price: "40k",
    timeStamp: "1hr",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/batman-mech-suit.jpeg",
  },
  {
    franchise: "DC",
    from: "Justice league Batman v superman",
    name: "supermans coffin",
    price: "100k",
    timeStamp: "2hr",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/superman-coffin.jpeg",
  },
  {
    franchise: "DC",
    from: "Justice league Batman v superman",
    name: "Kryptonite spear",
    price: "15k",
    timeStamp: "1hr",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/kryptonit-spear.png",
  },
  {
    franchise: "DC",
    from: "Dark Knight",
    name: "Bat Mobile",
    price: "100k",
    timeStamp: "10min",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/batmobile.jpeg",
  },
  {
    franchise: "DC",
    from: "Dark Knight",
    name: "Jokers playing card",
    price: "1k",
    timeStamp: "1hr 20min",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/joker-card.png",
  },
  {
    franchise: "DC",
    from: "flash",
    name: "Flash ring",
    price: "5k",
    timeStamp: "15min",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/flash-ring.jpeg",
  },
  {
    franchise: "DC",
    from: "flash",
    name: "Flash suit",
    price: "50k",
    timeStamp: "5min",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/flash-suit.jpeg",
  },
  {
    franchise: "DC",
    from: "flash",
    name: "Batflash suit",
    price: "30k",
    timeStamp: "2hr 45min",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/bat-flash-suit.png",
  },
  {
    franchise: "Star wars",
    from: "New hope",
    name: "luke‘s lightsaber (green)",
    price: "75k",
    timeStamp: "5min",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/lukes-saber.jpeg",
  },
  {
    franchise: "Star wars",
    from: "New hope",
    name: "R2-D2",
    price: "50k",
    timeStamp: "5min",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/r2-d2.jpeg",
  },
  {
    franchise: "Star wars",
    from: "New hope",
    name: "Death star mini prop",
    price: "5k",
    timeStamp: "20min",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/death-star-min.jpeg",
  },
  {
    franchise: "Star wars",
    from: "Revenge of the sith",
    name: "Darth vader mask",
    price: "25K",
    timeStamp: "2hr",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/darth-vader-mask.jpeg",
  },
  {
    franchise: "Star wars",
    from: "Revenge of the sith",
    name: "Purple lightsaber",
    price: "20K",
    timeStamp: "50min",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/mace-windus-saber.png",
  },
  {
    franchise: "Star wars",
    from: "Revenge of the sith",
    name: "anakins cloak",
    price: "20k",
    timeStamp: "1hr",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/vaders-cloak.jpeg",
  },
  {
    franchise: "Star wars",
    from: "Rise of skywalkers",
    name: "KYLO rens light saber",
    price: "40k",
    timeStamp: "1hr 45min",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/kylo-rens-saber.jpeg",
  },
  {
    franchise: "Star wars",
    from: "Rise of skywalkers",
    name: "KYLO rens mask",
    price: "15k",
    timeStamp: "25min",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/kylo-rens-mask.jpeg",
  },
  {
    franchise: "Star wars",
    from: "Rise of skywalkers",
    name: "Lukes light saber(blue)",
    price: "100k",
    timeStamp: "1hr 45min",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/lukes-blue-saber.png",
  },
  {
    franchise: "Star wars",
    from: "Rise of skywalkers",
    name: "THE George lucas",
    price: "0.65c",
    timeStamp: "all time",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/george-lucas.jpeg",
  },

  {
    franchise: "Harry potter",
    from: "Sorcerer's stone",
    name: "Harrys wand",
    price: "30k",
    timeStamp: "10min",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/harrys-wand.jpeg",
  },
  {
    franchise: "Harry potter",
    from: "Sorcerer's stone",
    name: "harrys owls cage",
    price: "30k",
    timeStamp: "45min",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/owl-cage.png",
  },
  {
    franchise: "Harry potter",
    from: "Sorcerer's stone",
    name: "Invisibility cloak",
    price: "100mil",
    timeStamp: "30min",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/invisibility-cloak.jpeg",
  },
  {
    franchise: "Harry potter",
    from: "Rise of the phoenix",
    name: "Death eater mask",
    price: "15k",
    timeStamp: "30min",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/death-eater-mask.png",
  },
  {
    franchise: "Harry potter",
    from: "Rise of the phoenix",
    name: "Harry potters glasses",
    price: "500k",
    timeStamp: "1min",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/harrys-glasses.png",
  },
  {
    franchise: "Harry potter",
    from: "Rise of the phoenix",
    name: "Hall of prophecy orb",
    price: "60k",
    timeStamp: "10min",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/hall-of-prophecy-orb.jpeg",
  },
  {
    franchise: "Harry potter",
    from: "Deathly hallows",
    name: "voldamorts wand",
    price: "100k",
    timeStamp: "1hr",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/voldomorts-wand.png",
  },
  {
    franchise: "Harry potter",
    from: "Deathly hallows",
    name: "The noble collection",
    price: "10k",
    timeStamp: "30min",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/the-nobel-collection.jpeg",
  },
  {
    franchise: "Harry potter",
    from: "Deathly hallows",
    name: "Death eater wand",
    price: "60k",
    timeStamp: "2hr",
    src: "https://the-collector-images.s3.us-east-2.amazonaws.com/death-eater-wand.jpeg",
  },
];
async function populate() {
  await prisma.franchise.createMany({
    data: franchiseArr,
  });
  await prisma.item.createMany({
    data: itemArr,
  });
}
populate();
